### ISSUE TITLE
无法运行抽奖

### ISSUE THREAD

**Issue by luobolaoye** [LeoChen98/BiliRaffle#3603]
目前版本无法识别目前新版动态带opus的链接，只能手动还原成原版t.bilibili的链接

此外点击抽奖后，闪退，换了三台电脑都不行
系统是win11、win10

**Comment by LeoChen98** [comment]
问题已定位

**Comment by LeoChen98** [comment]
请下载新版本重试 [1.0.20.22](https://github.com/LeoChen98/BiliRaffle/releases/tag/1.0.20.22)

**Comment by luobolaoye** [comment]
最新版仍然闪退，无法读取带opus的链接

**Comment by LeoChen98** [comment]
请提供更多信息包括你的抽奖地址和设置；目前我这里无法再现闪退的问题

**Comment by luobolaoye** [comment]
抽奖地址：https://www.bilibili.com/opus/789166087313817609
手动转换的地址：https://t.bilibili.com/789166087313817609
刚才又输入了一次，提示如图
![image](https://user-images.githubusercontent.com/93113746/236463523-5471c4cc-7dbe-4bba-abaf-5af13128f977.png)

**Comment by luobolaoye** [comment]
上面手动转换过的地址开始抽奖后依然闪退

**Comment by LeoChen98** [comment]
你好，这是转发太多了，访问过于频繁触发了B站的风控，这边建议大转发量抽奖使用官方工具。见 #46

**Comment by luobolaoye** [comment]
没到500条应该不至于吧，用另一个插件也完成了抽奖
https://www.bilibili.com/opus/792146944943194131

**Comment by luobolaoye** [comment]
![image](https://user-images.githubusercontent.com/93113746/236465718-492ed808-d242-44bc-a8fe-d7e4e02af5de.png)
又拿这个插件抽了另一个动态，仍然是可以使用。但BiliRaffle还是闪退

**Comment by luobolaoye** [comment]
另一个抽奖插件是这个https://gitee.com/ikaros-521/bilibili_draw/releases/tag/v4.0

**Comment by LeoChen98** [comment]
那就不懂了，我看了代码，我们用的接口都是一样的，很谜
