### ISSUE TITLE
有没有计划在抽奖条件里加一个点赞功能

### ISSUE THREAD

**Issue by shoyu3** [LeoChen98/BiliRaffle#511]
动态点赞列表用的api：
https://api.vc.bilibili.com/dynamic_like/v1/dynamic_like/spec_item_likes?dynamic_id=[动态ID]&pn=[页数]
假如我会写C#的话可能就直接提交PR了……

但是如果要获取视频的点赞信息，需要cookie和后台消息专用的cardID，不太清楚要怎么查询获得这个ID

另外给个建议，在登录完成后开始获取动态（或视频等）的转发（或评论）列表之前应该要校验一下发布内容的用户是否和当前登录的一致，如果不一致就报错（这种情况应该只有抽奖条件需要关注多个号才会出现，但很明显程序并不是也不会为这些极少的特殊条件专门去设计，当然也可以设置个选项自由选择）

**Comment by LeoChen98** [comment]
没有，因为评论和转发就已经获取不过来了，破站有风控，短时间获取大量数据不现实，再做点赞几乎就是100%风控，没有可行性。

**Comment by shoyu3** [comment]
> 没有，因为评论和转发就已经获取不过来了，破站有风控，短时间获取大量数据不现实，再做点赞几乎就是100%风控，没有可行性。

没有那么严重，我调试几天下来只有评论的获取频率不能太快，其他的都没有怎么被封过，除非是想帮人家节约服务器压力:smirk:

**Comment by shoyu3** [comment]
> 没有，因为评论和转发就已经获取不过来了，破站有风控，短时间获取大量数据不现实，再做点赞几乎就是100%风控，没有可行性。

还有，现在的最新版本在我电脑上经常崩溃，要不要看看怎么解决？
![image](https://user-images.githubusercontent.com/75879378/113146368-2a5b2a00-9262-11eb-8408-5468983d0a02.png)
[Report.wer.zip](https://github.com/LeoChen98/BiliRaffle/files/6236630/Report.wer.zip)

**Comment by LeoChen98** [comment]
> > 没有，因为评论和转发就已经获取不过来了，破站有风控，短时间获取大量数据不现实，再做点赞几乎就是100%风控，没有可行性。
> 
> 还有，现在的最新版本在我电脑上经常崩溃，要不要看看怎么解决？
> ![image](https://user-images.githubusercontent.com/75879378/113146368-2a5b2a00-9262-11eb-8408-5468983d0a02.png)
> [Report.wer.zip](https://github.com/LeoChen98/BiliRaffle/files/6236630/Report.wer.zip)

System.Net.WebException，应该就是412错误

**Comment by shoyu3** [comment]
> > > 没有，因为评论和转发就已经获取不过来了，破站有风控，短时间获取大量数据不现实，再做点赞几乎就是100%风控，没有可行性。
> > 
> > 
> > 还有，现在的最新版本在我电脑上经常崩溃，要不要看看怎么解决？
> > ![image](https://user-images.githubusercontent.com/75879378/113146368-2a5b2a00-9262-11eb-8408-5468983d0a02.png)
> > [Report.wer.zip](https://github.com/LeoChen98/BiliRaffle/files/6236630/Report.wer.zip)
> 
> System.Net.WebException，应该就是412错误

说得有点隐晦……我还是用我自己写的抽奖工具吧
